-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.department
(
    department_id integer NOT NULL,
    department_name character varying(30) NOT NULL,
    PRIMARY KEY (department_id)
);

CREATE TABLE public.employees
(
    employe_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    identy_number integer NOT NULL,
    user_id integer NOT NULL,
    date_of_registration date,
    PRIMARY KEY (employe_id)
);

CREATE TABLE public.employers
(
    employers_id integer NOT NULL,
    name character varying(50) NOT NULL,
    website character varying(50) NOT NULL,
    telephone integer NOT NULL,
    user_id integer NOT NULL,
    " date_of_registration" date,
    PRIMARY KEY (employers_id)
);

CREATE TABLE public.system_employees
(
    system_employe_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    user_id integer NOT NULL,
    date_of_registration date,
    PRIMARY KEY (system_employe_id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    e_mail character(1) NOT NULL,
    password character varying NOT NULL,
    is_verified boolean,
    PRIMARY KEY (user_id)
);

COMMENT ON TABLE public.users
    IS 'Sisteme giriş yapan tüm kullanıcılar.';

ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.system_employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;

END;